dist: trusty	

language: php	

php:	
  - 7.4
matrix:	
  fast_finish: true	

sudo: false	

install:	
  - composer --version	
  - composer install --dev -vvv	

script:	
  - composer test	

after_success:	
  - bash <(curl -s https://codecov.io/bash)